FROM haproxy:2.4-alpine
USER root
RUN mkdir -p /var/lib/haproxy && \
    chown -R "haproxy:haproxy" /var/lib/haproxy
# declare configs envs
ENV HAPROXY_USER=haproxy

# copy configs
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

# start with the specified configs
CMD ["haproxy", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
