version: "3.6"
services:
  mk-next:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    image: mk-next
    # volumes:
    # - mk-next-img:/app/.next/cache/images
    env_file:
      - ../.env
    container_name: mk-next
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - mk_prod
 

  mk-haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile.prod
    image: mk-haproxy
    depends_on:
      - mk-next
    container_name: mk-haproxy
    restart: unless-stopped
    volumes:
      - ./ssl/cf/haproxy_ecc.pem:/etc/haproxy/ssl/haproxy_ecc.pem:ro
      - ./ssl/cf/priv.key:/etc/haproxy/ssl/priv.key:ro
      - ./ssl/dh/dhparam-2048.pem:/etc/haproxy/ssl/dhparam-2048.pem:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - mk_prod

networks:
  mk_prod:

      #volumes:
      #mk-next-img:
      #driver: local
      #name: mk-next-img
