version: "3.6"
services:
  mk-next:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    image: mk-next
    # volumes:
    # - mk-next-img:/app/.next/cache/images
    env_file:
      - ../.env
    container_name: mk-next
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - mk_prod
 

  mk-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: mk-nginx
    depends_on:
      - mk-next
    container_name: mk-nginx
    restart: unless-stopped
    volumes:
      - ./ssl/cf/ecc.pem:/etc/nginx/ssl/ecc.pem:ro
      - ./ssl/cf/priv.key:/etc/nginx/ssl/priv.key:ro
      - ./ssl/dh/dhparam-2048.pem:/etc/nginx/ssl/dhparam-2048.pem:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mk_prod

networks:
  mk_prod:

      #volumes:
      #mk-next-img:
      #driver: local
      #name: mk-next-img
