version: "3.6"
services:
  mk-next:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    image: mk-next
    env_file:
      - ../.env
    container_name: mk-next
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - mk_prod
 

  mk-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: mk-nginx
    depends_on:
      - mk-next
    container_name: mk-nginx
    restart: unless-stopped
    volumes:
      - /etc/ssl/mkreg/cf/ecc.pem:/etc/nginx/ssl/ecc.pem:ro
      - /etc/ssl/mkreg/cf/priv.key:/etc/nginx/ssl/priv.key:ro
      - /etc/ssl/mkreg/cf/ca_root.pem:/etc/nginx/ssl/ca_root.pem:ro
      - /etc/ssl/mkreg/dh/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mk_prod

networks:
  mk_prod:
