# Stage 1: Building the code
FROM mhart/alpine-node AS builder

WORKDIR /mk

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
